

```{r}
#shallow water subset
shallow <- subset(nitrogen_data, Zone == "Shallow")

#mesophotic subset
mesophotic <- subset(nitrogen_data, Zone == "Mesophotic")
```

```{r}
#MHI subset
MainHI <- subset(nitrogen_data, Region == "MHI")

#NWHI subset
NwestHI <- subset(nitrogen_data, Region == "NWHI")
```

```{r}
#MHI subsets
MHI.shlw <- subset(MainHI, Zone == "Shallow")
MHI.meso <- subset(MainHI, Zone == "Mesophotic")

Oahu <- subset(MainHI, Location =="Oahu")
Maui <- subset(MainHI, Location =="Maui")
Niihau <- subset(MainHI, Location =="Niihau")
Molokai.meso <- subset(MainHI, Location =="Molokai")
Oahu.shlw <- subset(MHI.shlw, Location =="Oahu")
Maui.shlw <- subset(MHI.shlw, Location == "Maui")
Oahu.meso <- subset(MHI.meso, Location =="Oahu")
Maui.meso <- subset(MHI.meso, Location =="Maui")


#NWHI subset
NWHI.shlw <- subset(NwestHI, Zone =="S")
NWHI.meso <- subset(NwestHI, Zone =="M")
```

```{r}
Halimeda <- subset(all_halimeda, Genus == "Halimeda sp.")
Halimeda_MHI <- subset(Halimeda, Region == "MHI")
Hali_MHI_shlw <- subset(Halimeda_MHI, Zone == "Shallow")
Hali_MHI_meso <- subset(Halimeda_MHI, Zone == "Mesophotic")
Halimeda_NWHI <- subset(Halimeda, Region == "NWHI")
all_MHI <- subset(all_halimeda, Region == "MHI")
all_halimeda_shlw <- subset(all_MHI, Zone == "Shallow")
all_halimeda_meso <- subset(all_MHI, Zone == "Mesophotic")
```

```{r}
best_shlw <- subset(best_genera, Zone == "Shallow")
best_meso <- subset(best_genera, Zone == "Mesophotic")
```


```{r}
write.csv(MHI.shlw, ".\\MHI.shlw.csv")
write.csv(MHI.meso, ".\\MHI.meso.csv")
write.csv(NWHI.shlw, ".\\NWHI.shlw.csv")
write.csv(NWHI.meso, ".\\NWHI.meso.csv")
```

