```{r}
library(ggplot2)

# Region Violin Plots

ggplot(nitrogen_data, aes(x=Region, y=N15, fill=Region)) + geom_violin() + 
scale_fill_manual(values = c("red2", 'forestgreen')) + 
labs(y= expression(paste(delta^{15}, 'N (‰)'), x = 'Region')) +
theme(axis.title = element_text(size = 15)) + 
theme(axis.text = element_text(size = 12)) + 
theme(legend.title =  element_text(size = 15)) + 
theme(legend.text = element_text(size = 12))
ggsave("N15 ~ Region.png", dpi=300)

ggplot(nitrogen_data, aes(x=Region, y=Percent, fill=Region)) + geom_violin()+ scale_fill_manual(values = c("red2", 'forestgreen')) + labs(y= 'N (%)', x = 'Region') +
theme(axis.title = element_text(size = 15)) + 
theme(axis.text = element_text(size = 12)) + 
theme(legend.title =  element_text(size = 15)) + 
theme(legend.text = element_text(size = 12))
ggsave("Percent ~ Region.png", dpi=300)

```

```{r}
# Region split up by zone violin plots

ggplot(Violin_plots, aes(x=Region, y=N15, fill=Zone)) + 
geom_violin() +
scale_fill_manual(values = c("deepskyblue1", 'darkblue'), labels = c('Shallow', 'Mesophotic')) + 
labs(y= expression(paste(delta^{15}, 'N (‰)'), x = 'Region')) +
theme(axis.title = element_text(size = 15)) + 
theme(axis.text = element_text(size = 12)) + 
theme(legend.title =  element_text(size = 15)) + 
theme(legend.text = element_text(size = 12))
ggsave("N15 ~ Region-Zone.png", dpi=300)

ggplot(Violin_plots, aes(x=Region, y=Percent, fill=Zone)) + geom_violin() +
scale_fill_manual(values = c("deepskyblue1", 'darkblue'), labels = c('Shallow', 'Mesophotic')) +
labs(y= 'N (%)', x = 'Region') +
theme(axis.title = element_text(size = 15)) + 
theme(axis.text = element_text(size = 12)) + 
theme(legend.title =  element_text(size = 15)) + 
theme(legend.text = element_text(size = 12))
ggsave("Percent ~ Region-Zone.png", dpi=300)
```


```{r}
# Halimeda sp. vs kanaloana violin plots

ggplot(all_halimeda, aes(x=Genus, y=N15, fill=Zone)) + geom_violin() + scale_fill_manual(values = c('darkblue', "deepskyblue1")) + labs(y= expression(paste(delta^{15}, 'N (‰)'), x = 'Genus'))
ggplot(all_halimeda, aes(x=Genus, y=Percent, fill=Zone)) + geom_violin()+ scale_fill_manual(values = c('darkblue', "deepskyblue1")) + labs(y= 'N (%)', x = 'Genus')
```


Code below here was for exploratory purposes

```{r}
#plot of Zones across the MHI

ggplot(MainHI, aes(x=Zone, y=N15, fill=Zone)) + geom_violin(trim = FALSE)

ggplot(MainHI, aes(x=Zone, y=Percent, fill=Zone)) + geom_violin(trim = FALSE)

```



```{r}
#Plots of shallow mhi 
ggplot(MHI.shlw, aes(x=Genus, y=N15, fill=Genus)) + geom_violin(trim = FALSE)
ggplot(MHI.shlw, aes(x=Genus, y=Percent, fill=Genus)) + geom_violin(trim = FALSE)

ggplot(MHI.shlw, aes(x=Location, y=N15, fill=Location)) + geom_violin(trim = FALSE)
ggplot(MHI.shlw, aes(x=Location, y=Percent, fill=Location)) + geom_violin(trim = FALSE)

ggplot(MHI.shlw, aes(x=as.factor(Depth), y=N15, fill=Depth)) + geom_violin(trim = FALSE)
ggplot(MHI.shlw, aes(x=as.factor(Depth), y=Percent, fill=Depth)) + geom_violin(trim = FALSE)
```

```{r}
ggplot(MHI.meso, aes(x=Location, y=N15, fill=Location)) + geom_violin(trim = FALSE)
ggplot(MHI.meso, aes(x=Location, y=Percent, fill=Location)) + geom_violin(trim = FALSE)
```

```{r}
ggplot(Oahu, aes(x=Zone, y=N15, fill=Zone)) + geom_violin(trim = FALSE)
ggplot(Oahu, aes(x=Zone, y=Percent, fill=Zone)) + geom_violin(trim = FALSE)

ggplot(Maui, aes(x=Zone, y=N15, fill=Zone)) + geom_violin(trim = FALSE)
ggplot(Maui, aes(x=Zone, y=Percent, fill=Zone)) + geom_violin(trim = FALSE)
```

```{r}
ggplot(Oahu, aes(x=Zone, y=N15, fill=Genus)) + geom_violin(trim = FALSE)
ggplot(Oahu, aes(x=Zone, y=Percent, fill=Genus)) + geom_violin(trim = FALSE)

ggplot(Oahu, aes(x=Depth, y=N15, fill=Depth)) + geom_violin(trim = FALSE)
ggplot(Oahu, aes(x=Depth, y=Percent, fill=Depth)) + geom_violin(trim = FALSE)


ggplot(Maui, aes(x=Zone, y=N15, fill=Genus)) + geom_violin(trim = FALSE)
ggplot(Maui, aes(x=Zone, y=Percent, fill=Genus)) + geom_violin(trim = FALSE)

ggplot(Maui, aes(x=Depth, y=N15, fill=Depth)) + geom_violin(trim = FALSE)
ggplot(Maui, aes(x=Depth, y=Percent, fill=Depth)) + geom_violin(trim = FALSE)
```

```{r}
ggplot(Molokai.meso, aes(x=Depth, y=N15, fill=Genus)) + geom_violin(trim = FALSE)
ggplot(Molokai.meso, aes(x=Depth, y=Percent, fill=Genus)) + geom_violin(trim = FALSE)
```

```{r}
ggplot(Halimeda.MHI, aes(x=Location, y=N15, fill=Zone)) + geom_violin(trim = FALSE)
ggplot(Halimeda.MHI, aes(x=Location, y=Percent, fill=Zone)) + geom_violin(trim = FALSE)
```

